[project]
protostar-version = "0.9.1"
lib-path = "lib"
cairo-path = [
    "./lib/cairo_contracts/src"
]

[contracts]
DVT = ["src/DamnValuableToken.cairo"]

NAIVE_RECEIVER_LENDER_POOL = ["src/naive_receiver/NaiveReceiverLenderPool.cairo"]
FLASH_LOAN_RECEIVER = ["src/naive_receiver/FlashLoanReceiver.cairo"]
